In [2]:
from transformers import AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
sequences = [
    "I've been waiting for a EmKa Academy course my whole life.",
    "This course is amazing!"
]
batch = tokenizer(sequences, padding= True, truncation= True, return_tensors = "tf")
batch

{'input_ids': <tf.Tensor: shape=(2, 17), dtype=int32, numpy=
array([[ 101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 7861, 2912, 2914,
        2607, 2026, 2878, 2166, 1012,  102],
       [ 101, 2023, 2607, 2003, 6429,  999,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0]])>, 'token_type_ids': <tf.Tensor: shape=(2, 17), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(2, 17), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>}

In [3]:
from transformers import AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenizer("My name is Emincan" , "I work at EmKa Academy")

{'input_ids': [101, 2026, 2171, 2003, 12495, 20909, 2078, 102, 1045, 2147, 2012, 7861, 2912, 2914, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [4]:
from transformers import AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenizer(
    ["My name is Emincan", "Playing the basketball"],
    ["I work at EmKa Academy.", "This movie is great."],
    padding= True
) # It take pairs of sentence. token_type_ids shows that input_id belongs which sentence.

{'input_ids': [[101, 2026, 2171, 2003, 12495, 20909, 2078, 102, 1045, 2147, 2012, 7861, 2912, 2914, 1012, 102], [101, 2652, 1996, 3455, 102, 2023, 3185, 2003, 2307, 1012, 102, 0, 0, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]]}

In [5]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
batch = tokenizer(
    ["My name is Sylvain." , "Going to the cinamea."],
    ["I work at Hugging Face." , "This movie is great."],
    padding= True,
    return_tensors= "tf"
)

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**batch)
outputs

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.4058929,  0.1153729],
       [-0.3251912,  0.028024 ]], dtype=float32)>, hidden_states=None, attentions=None)

In [7]:
import tensorflow as tf

tf.math.softmax(outputs.logits, axis = -1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.3725563 , 0.62744373],
       [0.41260296, 0.58739704]], dtype=float32)>

In [ ]:
# Done